/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#eff1f3",
        "primary-container": "#2563eb",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#00174b",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-secondary-fixed": "#002113",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6cf8bb",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "on-secondary-fixed-variant": "#005236",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "tertiary": "#525657",
        "on-error-container": "#93000a",
        "secondary-fixed": "#6ffbbe",
        "surface": "#f8f9ff",
        "tertiary-container": "#6b6e70",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "error": "#ba1a1a",
        "primary": "#004ac6",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed-variant": "#444749",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#e0e3e5",
        "secondary": "#006c49",
        "inverse-primary": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "outline": "#737686",
        "on-primary-container": "#eeefff",
        "background": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4c5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "2xl": "48px",
        "lg": "24px",
        "margin-mobile": "16px",
        "base": "4px",
        "xs": "4px",
        "md": "16px",
        "3xl": "64px",
        "xl": "32px",
        "gutter": "24px",
        "container-max": "1280px",
        "sm": "8px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
