/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // === Brand Palette ===
        primary: {
          DEFAULT: "#10B981",
          50:  "#ECFDF5",
          100: "#D1FAE5",
          200: "#A7F3D0",
          300: "#6EE7B7",
          400: "#34D399",
          500: "#10B981",
          600: "#059669",
          700: "#047857",
          800: "#065F46",
          900: "#064E3B",
        },
        teal: {
          DEFAULT: "#14B8A6",
          50:  "#F0FDFA",
          100: "#CCFBF1",
          200: "#99F6E4",
          300: "#5EEAD4",
          400: "#2DD4BF",
          500: "#14B8A6",
          600: "#0D9488",
          700: "#0F766E",
          800: "#115E59",
          900: "#134E4A",
        },
        accent: {
          DEFAULT: "#3B82F6",
          50:  "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },

        // === Semantic tokens (resolved from CSS vars) ===
        background:       "var(--color-bg)",
        surface:          "var(--color-surface)",
        "surface-muted":  "var(--color-surface-muted)",
        border:           "var(--color-border)",
        "border-muted":   "var(--color-border-muted)",
        "text-primary":   "var(--color-text)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted":     "var(--color-text-muted)",
        "text-inverse":   "#FFFFFF",

        success:       "#22C55E",
        "success-bg":  "var(--color-success-bg)",
        warning:       "#F59E0B",
        "warning-bg":  "var(--color-warning-bg)",
        error:         "var(--color-error)",
        "error-bg":    "var(--color-error-bg)",
        info:          "#3B82F6",
        "info-bg":     "var(--color-info-bg)",

        // Legacy aliases kept for backward compat
        "on-tertiary-container":      "#F1F5F9",
        "primary-container":          "#D1FAE5",
        "surface-dim":                "#E2E8F0",
        "on-primary-fixed-variant":   "#047857",
        "inverse-surface":            "#0F172A",
        "on-primary-fixed":           "#064E3B",
        "primary-fixed":              "#D1FAE5",
        "on-secondary-fixed":         "#134E4A",
        "on-primary":                 "#FFFFFF",
        "surface-container-high":     "#E2E8F0",
        "surface-container-lowest":   "#FFFFFF",
        "secondary-container":        "#CCFBF1",
        "surface-container-low":      "#F8FAFC",
        "on-background":              "#0F172A",
        "on-secondary-fixed-variant": "#0F766E",
        "surface-container":          "#F1F5F9",
        "surface-bright":             "#FFFFFF",
        "error-container":            "#FEF2F2",
        "on-secondary":               "#FFFFFF",
        "on-tertiary-fixed":          "#0F172A",
        tertiary:                     "#64748B",
        "on-error-container":         "#DC2626",
        "secondary-fixed":            "#CCFBF1",
        "surface-variant":            "#E2E8F0",
        "secondary-fixed-dim":        "#99F6E4",
        "surface-tint":               "#10B981",
        "on-surface-variant":         "#64748B",
        "on-surface":                 "#0F172A",
        "inverse-on-surface":         "#F8FAFC",
        "tertiary-fixed":             "#F1F5F9",
        secondary:                    "#14B8A6",
        "inverse-primary":            "#6EE7B7",
        "outline-variant":            "#E2E8F0",
        outline:                      "#94A3B8",
        "on-primary-container":       "#064E3B",
        "surface-container-highest":  "#CBD5E1",
        "on-tertiary":                "#FFFFFF",
        "on-error":                   "#FFFFFF",
        "primary-fixed-dim":          "#6EE7B7",
        "tertiary-container":         "#94A3B8",
        "tertiary-fixed-dim":         "#CBD5E1",
      },

      borderRadius: {
        DEFAULT: "0.375rem",
        sm:    "0.25rem",
        md:    "0.375rem",
        lg:    "0.5rem",
        xl:    "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full:  "9999px",
      },

      spacing: {
        "xs":   "4px",
        "sm":   "8px",
        "md":   "16px",
        "lg":   "24px",
        "xl":   "32px",
        "2xl":  "48px",
        "3xl":  "64px",
        "gutter":        "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "base":          "4px",
      },

      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },

      fontSize: {
        "display-lg":        ["3.5rem",  { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md":        ["2.5rem",  { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":       ["2rem",    { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile":["1.5rem",  { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md":       ["1.5rem",  { lineHeight: "1.3",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm":       ["1.25rem", { lineHeight: "1.4",  fontWeight: "600" }],
        "title-lg":          ["1.125rem",{ lineHeight: "1.5",  fontWeight: "600" }],
        "title-md":          ["1rem",    { lineHeight: "1.5",  fontWeight: "600" }],
        "title-sm":          ["0.875rem",{ lineHeight: "1.5",  fontWeight: "600" }],
        "body-lg":           ["1rem",    { lineHeight: "1.6",  fontWeight: "400" }],
        "body-md":           ["0.875rem",{ lineHeight: "1.6",  fontWeight: "400" }],
        "body-sm":           ["0.8125rem",{ lineHeight:"1.5",  fontWeight: "400" }],
        "label-lg":          ["0.875rem",{ lineHeight: "1.4",  fontWeight: "500" }],
        "label-md":          ["0.8125rem",{ lineHeight:"1.4",  fontWeight: "500" }],
        "label-sm":          ["0.75rem", { lineHeight: "1.4",  fontWeight: "500" }],
      },

      boxShadow: {
        "ambient":    "0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px -1px rgba(0,0,0,0.06)",
        "card":       "var(--shadow-card)",
        "card-hover": "var(--shadow-hover)",
        "elevated":   "0 8px 32px 0 rgba(0,0,0,0.08)",
        "modal":      "var(--shadow-modal)",
        "primary":    "0 4px 12px 0 rgba(16,185,129,0.25)",
        "inner":      "inset 0 1px 0 rgba(255,255,255,0.12)",
        "none":       "none",
      },

      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #10B981 0%, #14B8A6 100%)",
        "gradient-accent":  "linear-gradient(135deg, #3B82F6 0%, #6366F1 100%)",
        "gradient-surface": "linear-gradient(180deg, #FFFFFF 0%, #F8FAFC 100%)",
        "gradient-hero":    "linear-gradient(135deg, #ECFDF5 0%, #F0FDFA 50%, #EFF6FF 100%)",
      },

      animation: {
        "fade-in":       "fadeIn 0.3s ease-out forwards",
        "fade-up":       "fadeUp 0.4s ease-out forwards",
        "slide-in-left": "slideInLeft 0.35s ease-out forwards",
        "scale-in":      "scaleIn 0.2s ease-out forwards",
        "spin-slow":     "spin 3s linear infinite",
        "pulse-soft":    "pulseSoft 2s ease-in-out infinite",
        "shimmer":       "shimmer 1.8s ease-in-out infinite",
        "float":         "float 3s ease-in-out infinite",
      },

      keyframes: {
        fadeIn:      { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        fadeUp:      { "0%": { opacity: "0", transform: "translateY(12px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideInLeft: { "0%": { opacity: "0", transform: "translateX(-16px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        scaleIn:     { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        pulseSoft:   { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.7" } },
        shimmer:     { "0%": { backgroundPosition: "-400px 0" }, "100%": { backgroundPosition: "400px 0" } },
        float:       { "0%, 100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-6px)" } },
      },

      transitionTimingFunction: {
        "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "smooth": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [],
}
